#docker compose commands here
version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/etc/nginx/certs:/etc/nginx/certs:ro"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true
  # letsencrypt-nginx:
  #   image: jrcs/letsencrypt-nginx-proxy-companion
  #   container_name: letsencrypt-nginx
  #   volumes:
  #     - "/etc/nginx/certs:/etc/nginx/certs:rw"
  #     - "/var/run/docker.sock:/var/run/docker.sock:ro"
  #   volumes_from:
  #     - "nginx-proxy"
  blue_ace_api:
    container_name: blue_ace_api
    build: ./blue_ace_api
    expose:
      - "8000"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
  blue_ace_app:
    container_name: blue_ace_app
    build: ./blue_ace_app
    expose:
      - "4200"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
